# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...commons.types.paging import Paging
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_list_subscriptions_list import GetListSubscriptionsList


class GetListSubscriptionsResponse(UncheckedBaseModel):
    paging: Paging
    results: typing.List[GetListSubscriptionsList] = pydantic.Field()
    """
    An array of lists
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
