# This file was auto-generated by Fern from our API Definition.

import typing

Reason = typing.Union[
    typing.Literal[
        "BOUNCED",
        "FAILED",
        "FILTERED",
        "NO_CHANNELS",
        "NO_PROVIDERS",
        "OPT_IN_REQUIRED",
        "PROVIDER_ERROR",
        "UNPUBLISHED",
        "UNSUBSCRIBED",
    ],
    typing.Any,
]
