# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .elemental_action_node import ElementalActionNode
from .elemental_divider_node import ElementalDividerNode
from .elemental_image_node import ElementalImageNode
from .elemental_meta_node import ElementalMetaNode
from .elemental_quote_node import ElementalQuoteNode
from .elemental_text_node import ElementalTextNode


class ElementalNode_Text(ElementalTextNode):
    type: typing_extensions.Literal["text"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ElementalNode_Meta(ElementalMetaNode):
    type: typing_extensions.Literal["meta"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ElementalNode_Channel(ElementalChannelNode):
    type: typing_extensions.Literal["channel"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ElementalNode_Image(ElementalImageNode):
    type: typing_extensions.Literal["image"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ElementalNode_Action(ElementalActionNode):
    type: typing_extensions.Literal["action"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ElementalNode_Divider(ElementalDividerNode):
    type: typing_extensions.Literal["divider"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ElementalNode_Group(ElementalGroupNode):
    type: typing_extensions.Literal["group"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ElementalNode_Quote(ElementalQuoteNode):
    type: typing_extensions.Literal["quote"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


ElementalNode = typing.Union[
    ElementalNode_Text,
    ElementalNode_Meta,
    ElementalNode_Channel,
    ElementalNode_Image,
    ElementalNode_Action,
    ElementalNode_Divider,
    ElementalNode_Group,
    ElementalNode_Quote,
]
from .elemental_channel_node import ElementalChannelNode  # noqa: E402
from .elemental_group_node import ElementalGroupNode  # noqa: E402

ElementalNode_Channel.update_forward_refs(
    ElementalChannelNode=ElementalChannelNode, ElementalGroupNode=ElementalGroupNode, ElementalNode=ElementalNode
)
ElementalNode_Group.update_forward_refs(
    ElementalChannelNode=ElementalChannelNode, ElementalGroupNode=ElementalGroupNode, ElementalNode=ElementalNode
)
