# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class Override(str, enum.Enum):
    MESSAGE_CHANNEL_EMAIL_OVERRIDE = "MessageChannelEmailOverride"
    MESSAGE_CHANNEL_PUSH_OVERRIDE = "MessageChannelPushOverride"

    def visit(
        self,
        message_channel_email_override: typing.Callable[[], T_Result],
        message_channel_push_override: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is Override.MESSAGE_CHANNEL_EMAIL_OVERRIDE:
            return message_channel_email_override()
        if self is Override.MESSAGE_CHANNEL_PUSH_OVERRIDE:
            return message_channel_push_override()
