# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....commons.types.channel_classification import ChannelClassification
from ....commons.types.preference_status import PreferenceStatus
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel


class TopicPreference(UncheckedBaseModel):
    custom_routing: typing.Optional[typing.List[ChannelClassification]] = pydantic.Field(default=None)
    """
    The Channels a user has chosen to receive notifications through for this topic
    """

    default_status: PreferenceStatus
    has_custom_routing: typing.Optional[bool] = None
    status: PreferenceStatus
    topic_id: str
    topic_name: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
