# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from .automation_step import AutomationStep


class AutomationAddToDigestStep(AutomationStep):
    """
    Examples
    --------
    from courier.automations import AutomationAddToDigestStep

    AutomationAddToDigestStep(
        subscription_topic_id="RAJE97CMT04KDJJ88ZDS2TP1690S",
    )
    """

    action: typing.Literal["add-to-digest"] = "add-to-digest"
    subscription_topic_id: str = pydantic.Field()
    """
    The subscription topic that has digests enabled
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
