# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .automation_fetch_data_webhook_method import AutomationFetchDataWebhookMethod


class AutomationFetchDataWebhook(UncheckedBaseModel):
    body: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    headers: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    params: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    method: AutomationFetchDataWebhookMethod
    url: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
