# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .brand_settings import BrandSettings
from .brand_snippets import BrandSnippets


class BrandParameters(UncheckedBaseModel):
    id: typing.Optional[str] = None
    name: str = pydantic.Field()
    """
    The name of the brand.
    """

    settings: BrandSettings
    snippets: typing.Optional[BrandSnippets] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
