# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from .brand_template import BrandTemplate


class BrandTemplateOverride(BrandTemplate):
    mjml: BrandTemplate
    footer_background_color: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="footerBackgroundColor")
    ] = None
    footer_full_width: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="footerFullWidth")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
