# This file was auto-generated by Fern from our API Definition.

from ...core.api_error import ApiError
from ..types.already_exists import AlreadyExists


class AlreadyExistsError(ApiError):
    def __init__(self, body: AlreadyExists):
        super().__init__(status_code=409, body=body)
